name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Frontend
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'
        
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install
      
    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test
      
    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build
